[env:hub_s3_supermini]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200

board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="sdkconfig.defaults"
board_build.partitions = partitions.csv

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -D CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE=0
